-- DEVUELVE EL CATALOGO DE TIPOS DE IDENTIFICACION
CREATE PROCEDURE SP_GetAllTipoIdentificacion
AS
BEGIN

	SELECT * FROM TipoIdentificacion WHERE estado = 'A';

END


--DEVUELVE EL CATALOGO DE TIPOS DE TARJETA
CREATE PROCEDURE SP_GetAllTipoTarjeta
AS
BEGIN

    SELECT * FROM TipoTarjeta WHERE estado = 'A';

END